apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: svastha-relay-data
  namespace: svastha
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage-retain
  resources:
    requests:
      storage: 5Gi
