apiVersion: v1
kind: Secret
metadata:
    name: svastha-relay-vapid
    namespace: svastha
type: Opaque
stringData:
    SVASTHA_RELAY_VAPID_PRIVATE: ENC[AES256_GCM,data:qLpQsMw41Zca+PHfA3z9uJc6JAGW9zLASAR7DYCdexHIPD0vPP8Sa6UyfA==,iv:Ry6UK2JcdkcE4izIjnK1szahK176VOgMMiVPnyd8X/8=,tag:42e+3s1wfDxD3hO1PSA+Ww==,type:str]
    SVASTHA_RELAY_VAPID_PUBLIC: ENC[AES256_GCM,data:lq5V2mq3/Y6BwgmF8T9xNm2Bwya/NI5aDzeufLZQM0LKxr7Uls9NV0j9dDHRNhv1AqpWpp7Z6MGKpxjx3aj9vbdOOPppZnHRyMYh0iR/yV9EJKle0uPb,iv:w/IMeTdSkAQ9KsuIcUUOeWi5g3ikgTSuhjx2OAqfxNI=,tag:R9XI6LqhQ9gFuT6rPmQPAw==,type:str]
    SVASTHA_RELAY_VAPID_SUBJECT: ENC[AES256_GCM,data:FZeBVsgEyVkPshzPHFgExOV85spsGxsBpq897GLfGw==,iv:3HCIPodF5kd2wf14LUmn1jgWTLq3/BelnxabUj+3+70=,tag:KDj1MivHV6jGeXuAT+yrrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TUFrY3k3UGZoNVFEM2Qz
            YXVvSmZpKzJsQ3VocE5McG5NSGZQYzBrb1Z3CnV4eTBpZk5yOXJQT1JtcDFVUU5J
            TklQRnl3V2daSDVtdkFyeDlmUUFubFEKLS0tIFlmWVFLcVZpRnZETUhmVGNNdU5q
            NWt1U0dvamJjcUlqb3Fnc0dMalhJZTgKXPc7UU4kktu3C/ZzkgFjbbJ8acmcFD7i
            3Rn3KZllxhWSvtL122mUj8q6Slvkbn8OCXGUgn8id4PCJH6BtVwFSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m06mlc98kyfx0ewtrmjezlgca2zvfp0qtdc6apeum9w387mdqc2qkkd0a2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T08:57:36Z"
    mac: ENC[AES256_GCM,data:YezxtqrsxPMub+8sRloOb0MfuEd/uRIZrR+b4+VXjQWZ7DYmgyakFFDpz2WZZLT3a1wBQthzn6gOEqdQqxFsxTPhHk1s9oScz2FToQ4vw/pm/QxtdpxW9dipDU4w7Cbk7t4v1EUXIrh5AuBm4DId3Gj96gZG3yqSy3BULxNuuPY=,iv:F7wwv+J54GVfCMfesekGiaS6aHdXrAGE2qwC+bW8Xs8=,tag:JDhiVqvn7VGDQKsjrYtBOQ==,type:str]
    version: 3.13.3
