apiVersion: v1
kind: Secret
metadata:
    name: pager-vapid
    namespace: pager
type: Opaque
stringData:
    vapid.json: ENC[AES256_GCM,data:cJMeJdYbKUkuw13f3T+rJco5hiXwck5SeeqfVxCiaCVnF7HjdXGwSiXPG29B8KuW+tQl7uhMwAqWexUQL5HDkwr7WOMa2+F8z/cLNbDzg6S2aCQld2HYjue3XwZd/gyNQWCkVoAQTP5d/IDfHAtLlWrP7GgShJtQC+9In0rg5fkrMYS2sCDrk2xeK0cCuKBymIUspjtKYG1oru+YqUOBVIlnJ4TaiWxvaYjLjxRMyoRJtlDEKwDp/pS7GBgA/8EqoN4c+8ZpTnhjIqgTiollvUMxuR3AbK9beLUGd1BDwgS+XVkbyntHzVJjJYJNEbP4KUxva8SRqaymoXmmqvggM4ggUI8TXi0sOrQZDcIn5sCo/TzFEJ+gNQjGNs5YwSyhbYQOL2t+b4gRM3afvdEAKYRNw64HYaEVAbV8h7GlJBIl+NsRfUaO57vJ6UivwP5X9TN7+7rOkKOGrKjEfzONmUsbEIw/HmHhyq9JnQ+F4mpjIGHbSukccpxQp29jTKRz9fALHXDuyLIaPYz2Q5n6q/+mnvN8ugPP4TTblPxbRrkjE/oe8QcU8vNjGG2U39ESKEYURTxRvNBkbNQFzseLLnShthTU9T2NiXyro8sDtO4bcMdW,iv:Pos2cGMFRhJkZO92AiYKg98LfZsx0FYOdj87oqQFcUA=,tag:eo1hzl84Em9bSkC1GxtyfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT0hUZ1Y2bkcyZUNWQzdr
            TFE5UDJsb3BKUkZjSDFXQXJlWkt3azBBeTFrCnFXa2N4TFo5Y1BvQWljbkRSc2py
            NHV6OWdNWS8vWkthcnZCUG82U2xBL0kKLS0tIGlOdUl6dHJKdmRhbUFEN29zbkh6
            T3pIK09qTVdBcTA3bmwyWTVxbkFDUjAKFp1+fZHCCpgRyBDYRK5BhOaurfh53uYk
            uSrAXNHK22A7KvWqeOfPpPmRHVtoZP1wfN+U5dEOEBkWkP0HSItNaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m06mlc98kyfx0ewtrmjezlgca2zvfp0qtdc6apeum9w387mdqc2qkkd0a2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T15:11:13Z"
    mac: ENC[AES256_GCM,data:K1KNrdcGra6RxBPmOAYZ1WMSc4HTG44D/gezEpzLji8gG2Vng1OCOoqj7A6YES09O62QJclhI0yts/GcIXw5idk6/3055AOAZTN8RZKztuWEjVYCFEhwPtrYOV89JtLiOZrtRbA2fWoy0hSgoii55sLvouLDo02orLegBj0Q/bQ=,iv:DWegqoH4P1At9Z7AOFUVwRUWEC9E3t4xvdW+GBI7J7c=,tag:aMut7GiEcnXI5NupKrTYbw==,type:str]
    version: 3.13.1
