apiVersion: v1
kind: Secret
metadata:
    name: openclaw-basic-auth
    namespace: openclaw
type: Opaque
stringData:
    auth: ENC[AES256_GCM,data:PsGlhhltuUXLIpVBQQa37AHaFC9JmbJnm3jpu5p3dFqpvivF0txG50pq6k+4ZprSnQ==,iv:BtCEFxJaGYeOEt7Jo6lzjX7wN2G0hT4+DzvCC+nztsY=,tag:5qi0ebyJB32oZ3UY6oIm0g==,type:str]
sops:
    age:
        - recipient: age1m06mlc98kyfx0ewtrmjezlgca2zvfp0qtdc6apeum9w387mdqc2qkkd0a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaFhPa2owaFhXNXZQSGxR
            WkRBekF1dnFrdkdLaFNJbjIxVlVzeUY0cERZCnpaUHlEQUFVZC9FOUtyTUJQRW5w
            Y0RHb04vTGltcDBFbUFkRU51UVQ2aW8KLS0tIHl0UExxNndZOGRwK0NrWVdNRXRv
            OEduSHEwNlI3UUN6N3VGM2VsZjR6bmMKfq3hvE/8rUlXB/PibaXdMn4zc6UhqlE8
            OS24cWCH99aNK43+pYXo9QCsqn4Ov2oZ2k/jc/MxvCPX0hdlfRYSaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T03:39:25Z"
    mac: ENC[AES256_GCM,data:yMDqR2z3h1Yj+VZHz7410SlV4CLkI9DXOirI5yY6GFanRWDXatC52Q6lEACxCphQ+4CIVosjdIuKYrQUu4KGwqVaqCJ0nlWes9G9ZuGRJjcGtqj7u6GPQAkLbqRKYX+8wRPdr8zXFYjDsoEAjy0/R3Ab4wNJd3V60ZAFupgT7sA=,iv:xZgh2V8T6s+VHzETp3XWcnDxUzeOuTVs2hHw4dnjRx0=,tag:FklT7qHNF47WHkieamSHvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
