apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secret
    namespace: openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_PASSWORD: ENC[AES256_GCM,data:4wuaC96XGUY9kUPKjbTECfLnFqBN728LQbk+4sox1LU=,iv:vRjRua8qhV1lYVrM/uawmxom6AoOwkjWdtZj4vj7720=,tag:ZbQf+loOPhbzYfxHZier+A==,type:str]
sops:
    age:
        - recipient: age1m06mlc98kyfx0ewtrmjezlgca2zvfp0qtdc6apeum9w387mdqc2qkkd0a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYWRMaUxXL2h1TWQwVndh
            cjNQc1R6b2dYUzh5U3YzcVNWWG9UNmJMU1V3Ck5QbFJwUStrUzZzSkNrR2srMFky
            SDdncnlwaW1EbmVXVThUYXVSZ1VOeWsKLS0tIFE5OVRNOVVuVG9udUpQSGt2RG8y
            cmhxSGVxOW9WSHZIVnM1dVM3WlVGWWcKkZGU0uRQxscP4Das4M/gDsQqRGHuo506
            taoN2D4MwohzXUQGL5PVVvHb0vmzKSfaXCw67u65F7Dl6UCGta8IuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T02:45:40Z"
    mac: ENC[AES256_GCM,data:YzxmAM5C24wTZlEiwDEAVCPNQ/Svke1hUBszWfds810Gbchw44pC0EMHEQmRc/N289W7kD99/QTONE+69TFpAQbtVcoBMGRuORKcorZw8h+WvR+8Q/nPObNa1kUZj4ZG1Gxd705TMKpcdd62BtMykj9LaMXheWzgzY46dQ7ammc=,iv:mYe9VYNNm7kSAj6axiNEnyztyX5ilgI9NmFCOSeXjBE=,tag:clzOaZFVsGpGQTi5gH1EdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
