apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secret
    namespace: openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_PASSWORD: ENC[AES256_GCM,data:4wuaC96XGUY9kUPKjbTECfLnFqBN728LQbk+4sox1LU=,iv:vRjRua8qhV1lYVrM/uawmxom6AoOwkjWdtZj4vj7720=,tag:ZbQf+loOPhbzYfxHZier+A==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:5f1WrScr63xYMPzatLUYRmEXEEFBdmzqHDnbQW+GLUBs6XpxcNer30kmedLI07Ei30LXfyhE5D6TVrXKX1g/qzaHGNILehduxA==,iv:IIHEQsnP7ewy/auMqaL1rxewy+WQPKCDc+uehJq00qI=,tag:auRHD9mGJ13JZCcdxAZfAg==,type:str]
sops:
    age:
        - recipient: age1m06mlc98kyfx0ewtrmjezlgca2zvfp0qtdc6apeum9w387mdqc2qkkd0a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYWRMaUxXL2h1TWQwVndh
            cjNQc1R6b2dYUzh5U3YzcVNWWG9UNmJMU1V3Ck5QbFJwUStrUzZzSkNrR2srMFky
            SDdncnlwaW1EbmVXVThUYXVSZ1VOeWsKLS0tIFE5OVRNOVVuVG9udUpQSGt2RG8y
            cmhxSGVxOW9WSHZIVnM1dVM3WlVGWWcKkZGU0uRQxscP4Das4M/gDsQqRGHuo506
            taoN2D4MwohzXUQGL5PVVvHb0vmzKSfaXCw67u65F7Dl6UCGta8IuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T23:09:57Z"
    mac: ENC[AES256_GCM,data:/WgxT5qBZwwA7TCr4Feh6d/hQKgeVzaDf8OqoypSmn7AxGdZPq0hgukEVRgxwX81NZjeM6A1ERq5iADXzwmJMtCcLFJrC299/1W/eeFu3Dyea3pstlW/6OGele1wmHozWRk2O711WV/ZaL1wvPweIkqCCLZydzlTTUnANNcbgW8=,iv:zxk+q+jMqDnS2RjyH6Nu/EpFmIKIlxrN1Ojurp5taw8=,tag:LR7WqnvLIX/cRQXW464KQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
