apiVersion: v1
kind: Secret
metadata:
    name: svastha-node-inference
    namespace: svastha-node
type: Opaque
stringData:
    SVASTHA_NODE_INFERENCE_ENDPOINT: ENC[AES256_GCM,data:/AB4YO296Fu3+1NT0q5mwuzqkicyARBB5rmI7Uhx,iv:zNSOinBPpDpFdqY02V/Qe5gL63PVLLl7IKV8OQAETUE=,tag:dyRIysCE42+qwsALEMM1+A==,type:str]
    SVASTHA_NODE_INFERENCE_MODEL: ENC[AES256_GCM,data:WrEBoKuMMTniVqzg4Fx/mMlEOo0=,iv:veC6HoJfVdGJE1cETnGbN0MBaqp5tRclxgshHihbjII=,tag:l+IdXYwV7yFHIqUlVVtC+Q==,type:str]
    SVASTHA_NODE_INFERENCE_API_KEY: ENC[AES256_GCM,data:xjVdhuxiKqRHXIRlrM3tN0XmYBVvYnAE/SfZAV1gI+CN1GI2acQEO6koqlCwygG/mtS2wxG3tNnPar92gmKAC/0OfbJJMbY=,iv:bSEXzx1KanrV1bymaL36y9H6ansI58HSv6VFpxCCmEI=,tag:/w5O/V53B/YDJnlhWUQPew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYzBPMjN0LzNmYzRXNVdw
            alRab00yN2xhc3J3N3R2Rkx0OWcxVkpNUkZnClNnOC8yMmVYNWpjQ3FJRWVnazRo
            WmlxbEVJN3o2THlUV3F5V0dGZjBTRWcKLS0tIGJXVGJpR2ROQmdJZXNNSlhFNVZw
            QlM0bUw2RmcrUkx6aTd2ejh2T2hKV1UKMBPpRdRmgn8lWC4PVumFXkMxLI7+VV0z
            J3rW8SBMwKHkLc6kjKAC3fdohT1sOPM5uB5wgVJeef0BUXPZzP5tPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m06mlc98kyfx0ewtrmjezlgca2zvfp0qtdc6apeum9w387mdqc2qkkd0a2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T10:02:51Z"
    mac: ENC[AES256_GCM,data:coCyndIzO34rZktwHlXcoEfx8mzyBBqsDLNbL1jMWBSwOo9L/MRz4A1sxJuE9iBFG2Z8YLSCF0yxJjRY/Vzym8EH11KcFAb/G9K9Ax74SLiZEdxXLRIqf/+KUSYJWc7BlbcNZU+UwOA/TbW6db+TPTzaTrF+Cp8sXkTEMDHDnUs=,iv:l6Vubhmfpvdl9XJyrreJ7olk4s/wHICZ3aHEtP2EmEY=,tag:2MClIWIimWv3iEXZLF0C6g==,type:str]
    version: 3.13.3
