apiVersion: v1
kind: Secret
metadata:
    name: svastha-node-inference
    namespace: svastha-node
type: Opaque
stringData:
    SVASTHA_NODE_INFERENCE_ENDPOINT: ENC[AES256_GCM,data:/AB4YO296Fu3+1NT0q5mwuzqkicyARBB5rmI7Uhx,iv:zNSOinBPpDpFdqY02V/Qe5gL63PVLLl7IKV8OQAETUE=,tag:dyRIysCE42+qwsALEMM1+A==,type:str]
    SVASTHA_NODE_INFERENCE_MODEL: ENC[AES256_GCM,data:WrEBoKuMMTniVqzg4Fx/mMlEOo0=,iv:veC6HoJfVdGJE1cETnGbN0MBaqp5tRclxgshHihbjII=,tag:l+IdXYwV7yFHIqUlVVtC+Q==,type:str]
    SVASTHA_NODE_INFERENCE_API_KEY: ENC[AES256_GCM,data:0xkg80s/sWY8gYHALmsZF+Meh8zYQv9dLvTAl2GMqwY45ZduF7M=,iv:I04Rrr7zJRL/iM31Vasq5DJgUnjsUF8uc7NgO6peuZ0=,tag:A3n5jwb59I3h3gN/NvTKmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYzBPMjN0LzNmYzRXNVdw
            alRab00yN2xhc3J3N3R2Rkx0OWcxVkpNUkZnClNnOC8yMmVYNWpjQ3FJRWVnazRo
            WmlxbEVJN3o2THlUV3F5V0dGZjBTRWcKLS0tIGJXVGJpR2ROQmdJZXNNSlhFNVZw
            QlM0bUw2RmcrUkx6aTd2ejh2T2hKV1UKMBPpRdRmgn8lWC4PVumFXkMxLI7+VV0z
            J3rW8SBMwKHkLc6kjKAC3fdohT1sOPM5uB5wgVJeef0BUXPZzP5tPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m06mlc98kyfx0ewtrmjezlgca2zvfp0qtdc6apeum9w387mdqc2qkkd0a2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T09:31:22Z"
    mac: ENC[AES256_GCM,data:ssxMq6O98O9SJn47e+U3p4grtJh/Jmh1rZDNPfGD3FkMdENdxghUvN8IzPg2IeTYtAZbbw4jgO0Uylckhx3Mj5zEwfV1U1HbkH1wucKslm3MJWNtmMZAlLn/CgSxggUjP33K3EOY+EyN0SROdAWmxrPj+QSbLdcgZRwoO89R6q0=,iv:6X3hKIRQAFAymv0dnzJO4pw+giyruwqv7EJfZc11BB0=,tag:zY5mWYqSrlA4NK+5Zs5noA==,type:str]
    version: 3.13.3
