apiVersion: v1
kind: Secret
metadata:
    name: tracon-hub-admit
    namespace: tracon
type: Opaque
stringData:
    TRACON_HUB_ADMIT: ENC[AES256_GCM,data:KUk1FeX900JoXpmAl8RGSfWvMa5uQfpHG8LxbmAz1gypSgd6uBL8NbD8GwOxrcza9j/iJ5McEW9Or1aH75FYcw==,iv:cVqQKik1BReMHDPhW8qSz6PMRxX4E83HhkfvDaiOjSk=,tag:xR2gDQnjAdOIBZHaN5wIJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZDQ0RkpEM0d6MjdoSHR0
            KzZxeXNaRlc3QnVGUkZPSnpoczluTE93aUdJClVkekVVREttVWV3YW1STlNoemh1
            Uk02VkFvY20zUzhZSExVWWJhMWIzZ1UKLS0tIFNzTGIzL0orTmRTNkNLUFdocUt0
            WlJwcXFHMStIeTB5V3NEdndvbDY5SEkK5f77dQB1Ku/LJb43tDjC4yYZ0r94aRlX
            QA1wNMue8Cm7Xxx6dbIX5OrC4JByJkVZGQJSHpyVs8/d4uGmFkAZcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m06mlc98kyfx0ewtrmjezlgca2zvfp0qtdc6apeum9w387mdqc2qkkd0a2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T20:43:05Z"
    mac: ENC[AES256_GCM,data:LMM4mrY3jD63T2swCxOPg9eMaCJmBUgOqQr7m0c7x3zkkmfjejtahaderv7dCn0/fj2mdgCfjyhXhtmuFi+9T23j3UFTd+hoJpP9sTa3dd4HZozimsyYHD9/GRxeFqwlL30/durZrgGOi3tf4/Z3p8ipwjy5hzKZRUYVmYFlXMw=,iv:YMiETxlJS8Wbbjpnp4EPBEv5bqLXKrZkLEHwssDl6ww=,tag:yTSjd2suZnuUapRF0Zn3nw==,type:str]
    version: 3.13.3
