apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - image-catalog.yaml
  - postgres-cluster.yaml
  - helmrepository.yaml
  - helmrelease.yaml
