apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres
    namespace: immich
type: Opaque
stringData:
    #ENC[AES256_GCM,data:JLwHSoakuxrctLddoC9C63vEZVYfUZMDarhexF09v4XUb4tPJ04oyI00iNI6bCT+0ePVK8H+,iv:GseeZtfMEsDFYvhkYKf87YtZuOfA2q0Cb3VdxFbPqgw=,tag:6aVzJKxp3iXiy2+SaS5uzg==,type:comment]
    #ENC[AES256_GCM,data:afTH78aoklZ6bCEIPJTlCE94qXgRHrRl8hmc0+YrhI65lez0Fvd/YVud3Q==,iv:AJVtpemIgA3e7XzHcIi4LIKLw4gvOQKMJBVFygJvR3Q=,tag:2r9WeQSC8Rd/QlcqoSF3Hw==,type:comment]
    password: ENC[AES256_GCM,data:Bs0HZysbTaz6/yIBveLGPdxt/x9dG5Xp6/L7sYMtSuJ2Ey8KzkPM/oe2EHg=,iv:VJ+aykxN8f/yKi/Hp3hXHkSaQv7QEFO//hkltze0X7k=,tag:cN6Xj6pvfH175TGZMDXZfA==,type:str]
sops:
    age:
        - recipient: age1m06mlc98kyfx0ewtrmjezlgca2zvfp0qtdc6apeum9w387mdqc2qkkd0a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMG94dXNkdHZsSExnam9K
            L0hoN2dXckEzU1FwSDcxTE9YVnV0anQybVVFCmJ5Mmk1ZGExZmt0Wi9HOE0wVkIx
            U2swL2JSSHNBT1JjVkEyakVwL084N3cKLS0tIHdINGxFazFNTEFCZzVHSVlzNnRu
            STkwbGVxK0tZVmlnUGFkb3hzUEYveEUKu5hylxzXZpTBDjRgIixjkf07Dyb09Bw3
            JMOg3Hwuo9roClGeaQBzhJr2xRER/ev1Es0EKbAUKICjoV2GZjiUgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T02:48:34Z"
    mac: ENC[AES256_GCM,data:ZsQ6oGu+AReIx3r0w5wv9wclG8U2CbNV5UU6z8qJB0r+qoWyW/dSfrwtdDrtray1VRU91zlB6m/K6bWOI/zY3Kk2k4E7LvmkWzfwDegIVucMLP/P3k3sTvcTC36irRc22V5Tgd9hs37GIkIUOZu10Yw0HChMq+kdq8iueNB8R2o=,iv:0MIrmaxpYg002+Z3hZYwF3vQfFEkRyHXE/95Tr8wYNE=,tag:Q/z+zRvU4Vyw+TDjo7uamw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
